import type { Metadata } from "next";
import "../styles/globals.css";
// import { ThemeProvider } from "@/components/ShadCN/ui/theme-provider";
 
export const metadata: Metadata = {
  title: "Xavantory",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <head />
    <body>
      {/* <ThemeProvider
        attribute="class"
        defaultTheme="light"
        enableSystem
        disableTransitionOnChange
      > */}
        {children}
      {/* </ThemeProvider> */}
    </body>
  </html>
  );
}
