import type { Metadata } from "next";
import "@/styles/globals.css";
import BaseNavbar from "@/components/baseComponents/ui/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Xavantory",
  description: "Generated by create next app",
};

export default function staffLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <BaseNavbar />
          {children}
         </main>
      </body>
    </html>
  );
}
