import type { Metadata } from "next";
import "@/styles/globals.css";
import Navbar from "@/components/adminComponents/ui/Navbar/Navbar";
import StaffSidebar from "@/components/staffComponents/ui/Sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Xavantory",
  description: "Generated by create next app",
};

export default function staffLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen w-screen bg-gray-100">
        <div className="flex h-screen">
          <Navbar role={"staff"} />
          <StaffSidebar />

          <div className="flex-grow p-6 ml-64 overflow-y-auto mt-16">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
